{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-02-04T13:28:09.039063Z",
     "start_time": "2025-02-04T13:28:08.597016Z"
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "E0000 00:00:1743668887.526996  569801 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "E0000 00:00:1743668887.531439  569801 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "### Successfully loaded configuration from /home/h039y17/Projects/AIA2/src/notebooks/../../config/configuration.yaml ###\n",
      "Timestamp: 20250403_102817\n",
      "### Using GPU (CUDA) ###\n"
     ]
    }
   ],
   "source": [
    "%load_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "import sys\n",
    "import os\n",
    "\n",
    "sys.path.append('..')\n",
    "import AIA\n",
    "\n",
    "config_path = os.path.join(os.path.dirname(os.path.abspath('__file__')), '..', '..', 'config', 'configuration.yaml')\n",
    "aia = AIA.AIA(config_path)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "ExecuteTime": {
     "start_time": "2025-02-04T13:28:21.891350Z"
    },
    "jupyter": {
     "is_executing": true
    }
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "### Starting batch of n=20 images ###\n",
      "### Processing extract_basic_image_features() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:04<00:00,  4.20it/s]\n",
      "/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py:203: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'True' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.\n",
      "  df_saved.loc[mask, col] = row[col]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "4.7679 seconds needed\n",
      "### Processing get_ocr_text() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 15%|█▌        | 3/20 [00:00<00:01,  9.78it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing OCR for ../../data/test_human_20/amazon_products-3529a29f.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/amazon_products-73dae760.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/brand_selfie-original_instagram-desperados_ByM_4H1CeqJ.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/brand_selfie-original_instagram-jimbeam_BxfqamDlOh4.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 40%|████      | 8/20 [00:00<00:00, 14.61it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing OCR for ../../data/test_human_20/brand_selfie-original_instagram-kettlechips_peH67bKlyv.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/cannes_awards-thumbnail_00000062.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/cannes_awards-thumbnail_00000213.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/cannes_awards-thumbnail_00000309.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 70%|███████   | 14/20 [00:00<00:00, 19.81it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing OCR for ../../data/test_human_20/cannes_awards-thumbnail_00000371.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/food-4_28.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/food-8_187.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/hotels-271224146.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/hotels-280766888-1.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/hotels-361837089.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " 85%|████████▌ | 17/20 [00:01<00:00, 20.76it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing OCR for ../../data/test_human_20/hotels-373287013.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/hotels-Ohla Barcelona номер 3.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/image_ads-159065.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/image_ads-84609.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "Error processing OCR for ../../data/test_human_20/unsplash_views-dEQkrNuzkEA.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:01<00:00, 10.27it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing OCR for ../../data/test_human_20/unsplash_views-jK_Ss_JuADU.jpg: OCR processing error: (1, 'Error in pixReadMemTiff: function not present Error in pixReadMem: tiff: no pix returned Error in pixaGenerateFontFromString: pix not made Error in bmfCreate: font pixa not made Error opening data file /home/h039y17/share/tessdata/eng.traineddata Please make sure the TESSDATA_PREFIX environment variable is set to your \"tessdata\" directory. Failed loading language \\'eng\\' Tesseract couldn\\'t load any languages! Could not initialize tesseract.')\n",
      "1.9518 seconds needed\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "### Processing extract_blur_value() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:01<00:00, 15.44it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.2999 seconds needed\n",
      "### Processing estimate_noise() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:03<00:00,  6.45it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3.1066 seconds needed\n",
      "### Processing calculate_contrast_of_brightness() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:02<00:00,  7.25it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2.7641 seconds needed\n",
      "### Processing calculate_image_clarity() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:01<00:00, 18.36it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.0943 seconds needed\n",
      "### Processing calculate_hue_proportions() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:01<00:00, 16.31it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1.2317 seconds needed\n",
      "### Processing get_color_features() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:03<00:00,  5.70it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3.5137 seconds needed\n",
      "### Processing get_composition_features() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:03<00:00,  5.40it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "3.7137 seconds needed\n",
      "### Processing get_figure_ground_relationship_features() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:07<00:00,  2.67it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "7.5010 seconds needed\n",
      "### Processing calculate_aesthetic_scores() ###\n",
      "Weights /home/h039y17/Projects/AIA2/src/AIA/weights/weights_mobilenet_aesthetic_0.07.hdf5 are not stored locally. Downloading...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/h039y17/Projects/AIA2/src/AIA/weights/weights_mobilenet_aesthetic_0.07.hdf5: 13.2MB [00:01, 9.59MB/s]                            \n",
      "I0000 00:00:1743668936.477303  569801 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 79086 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe, pci bus id: 0000:17:00.0, compute capability: 8.0\n",
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "W0000 00:00:1743668937.199835  570503 gpu_backend_lib.cc:579] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.\n",
      "Searched for CUDA in the following directories:\n",
      "  ./cuda_sdk_lib\n",
      "  ipykernel_launcher.runfiles/cuda_nvcc\n",
      "  ipykern/cuda_nvcc\n",
      "  \n",
      "  /usr/local/cuda\n",
      "  /home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc\n",
      "  /home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc\n",
      "  /home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tensorflow/python/platform/../../cuda\n",
      "  .\n",
      "You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.\n",
      "  0%|          | 0/20 [00:00<?, ?it/s]I0000 00:00:1743668938.554822  570462 service.cc:148] XLA service 0x7f1150020c60 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n",
      "I0000 00:00:1743668938.554845  570462 service.cc:156]   StreamExecutor device (0): NVIDIA A100 80GB PCIe, Compute Capability 8.0\n",
      "E0000 00:00:1743668938.754110  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668938.790035  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "  5%|▌         | 1/20 [00:00<00:13,  1.43it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/amazon_products-3529a29f.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668939.035752  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668939.069479  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 10%|█         | 2/20 [00:00<00:08,  2.23it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/amazon_products-73dae760.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668939.312220  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668939.332146  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 15%|█▌        | 3/20 [00:01<00:06,  2.75it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/brand_selfie-original_instagram-desperados_ByM_4H1CeqJ.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668939.569253  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668939.605015  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 20%|██        | 4/20 [00:01<00:05,  3.04it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/brand_selfie-original_instagram-jimbeam_BxfqamDlOh4.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668939.831046  570494 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668939.863323  570494 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 25%|██▌       | 5/20 [00:01<00:04,  3.30it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/brand_selfie-original_instagram-kettlechips_peH67bKlyv.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668940.100333  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668940.131262  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 30%|███       | 6/20 [00:02<00:04,  3.44it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/cannes_awards-thumbnail_00000062.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668940.370820  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668940.387340  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 35%|███▌      | 7/20 [00:02<00:03,  3.58it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/cannes_awards-thumbnail_00000213.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668940.621022  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668940.637273  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 40%|████      | 8/20 [00:02<00:03,  3.71it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/cannes_awards-thumbnail_00000309.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668940.868244  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668940.884246  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 45%|████▌     | 9/20 [00:02<00:02,  3.80it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/cannes_awards-thumbnail_00000371.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668941.107026  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668941.123897  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 50%|█████     | 10/20 [00:03<00:02,  3.91it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/food-4_28.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668941.339369  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668941.355268  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 55%|█████▌    | 11/20 [00:03<00:02,  4.03it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/food-8_187.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668941.646807  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668941.668423  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 60%|██████    | 12/20 [00:03<00:02,  3.73it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/hotels-271224146.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668941.896227  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668941.917258  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 65%|██████▌   | 13/20 [00:03<00:01,  3.81it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/hotels-280766888-1.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668942.142897  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668942.162801  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 70%|███████   | 14/20 [00:04<00:01,  3.89it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/hotels-361837089.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668942.387752  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668942.404047  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 75%|███████▌  | 15/20 [00:04<00:01,  3.96it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/hotels-373287013.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668942.623181  570494 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668942.639608  570494 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 80%|████████  | 16/20 [00:04<00:00,  4.04it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/hotels-Ohla Barcelona номер 3.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668942.862134  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668942.878104  570462 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 85%|████████▌ | 17/20 [00:04<00:00,  4.09it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/image_ads-159065.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668943.096067  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668943.112891  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 90%|█████████ | 18/20 [00:05<00:00,  4.14it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/image_ads-84609.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668943.770978  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668943.787091  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      " 95%|█████████▌| 19/20 [00:05<00:00,  2.69it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/unsplash_views-dEQkrNuzkEA.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1743668944.169430  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "E0000 00:00:1743668944.185621  570485 cuda_dnn.cc:522] Loaded runtime CuDNN library: 9.1.0 but source was compiled with: 9.3.0.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.\n",
      "100%|██████████| 20/20 [00:06<00:00,  3.28it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error processing ../../data/test_human_20/unsplash_views-jK_Ss_JuADU.jpg: Graph execution error:\n",
      "\n",
      "Detected at node StatefulPartitionedCall defined at (most recent call last):\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 197, in _run_module_as_main\n",
      "\n",
      "  File \"/usr/lib64/python3.9/runpy.py\", line 87, in _run_code\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel_launcher.py\", line 18, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelapp.py\", line 739, in start\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/tornado/platform/asyncio.py\", line 205, in start\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 601, in run_forever\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/base_events.py\", line 1905, in _run_once\n",
      "\n",
      "  File \"/usr/lib64/python3.9/asyncio/events.py\", line 80, in _run\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3048, in run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3103, in _run_cell\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3308, in run_cell_async\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3490, in run_ast_nodes\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/IPython/core/interactiveshell.py\", line 3550, in run_code\n",
      "\n",
      "  File \"/home/h039y17/tmp/ipykernel_569801/1998439686.py\", line 5, in <module>\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py\", line 136, in process_batch\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/src/notebooks/../AIA/core/nima_idealo.py\", line 83, in calculate_aesthetic_scores\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 562, in predict\n",
      "\n",
      "  File \"/home/h039y17/Projects/AIA2/myenv/lib64/python3.9/site-packages/keras/src/backend/tensorflow/trainer.py\", line 259, in one_step_on_data_distributed\n",
      "\n",
      "DNN library initialization failed. Look at the errors above for more details.\n",
      "\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_one_step_on_data_distributed_2079]\n",
      "9.4351 seconds needed\n",
      "### Processing visual_complexity() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:16<00:00,  1.24it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "16.1259 seconds needed\n",
      "### Processing self_similarity() ###\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "100%|██████████| 20/20 [00:06<00:00,  3.11it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "6.4290 seconds needed\n",
      "### Processing predict_coco_labels_yolo11() ###\n",
      "Weights /home/h039y17/Projects/AIA2/src/AIA/weights/yolov11n.pt are not stored locally. Downloading...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/h039y17/Projects/AIA2/src/AIA/weights/yolov11n.pt: 5.63MB [00:00, 7.63MB/s]                            \n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Error loading COCO labels: [Errno 2] No such file or directory: '../AIA/weights/coco.names'\n",
      "0.8102 seconds needed\n",
      "### Processing predict_imagenet_classes_yolo11() ###\n",
      "Weights /home/h039y17/Projects/AIA2/src/AIA/weights/yolo11n-cls.pt are not stored locally. Downloading...\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/h039y17/Projects/AIA2/src/AIA/weights/yolo11n-cls.pt: 5.80MB [00:00, 6.95MB/s]                            \n",
      "100%|██████████| 20/20 [00:01<00:00, 11.66it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2.6980 seconds needed\n",
      "### Finished batch of n=20 images ###\n",
      "### Final Excel versions saved to: ..\\\\..\\\\outputs\\\\/20250403_102817\\ ###\n"
     ]
    }
   ],
   "source": [
    "# Specify input directory\n",
    "aia.input_dir = os.path.join('..', '..', 'data', 'test_human_20')\n",
    "\n",
    "# Run the pipeline\n",
    "results, logs = aia.process_batch()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Save the results\n",
    "aia.save_results(results)\n",
    "aia.save_logs(logs)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "### Excel not specified. Using data from current run: 20250403_102817_results.xlsx ###\n"
     ]
    },
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: '..\\\\\\\\..\\\\\\\\outputs\\\\\\\\/20250403_102817\\\\/20250403_102817_results.xlsx'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43maia\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgenerate_pdf_from_excel\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[0;32m~/Projects/AIA2/src/notebooks/../AIA/pipeline/aia_pipeline.py:321\u001b[0m, in \u001b[0;36mAIA.generate_pdf_from_excel\u001b[0;34m(self, excel_path, output_pdf_path)\u001b[0m\n\u001b[1;32m    318\u001b[0m     output_pdf_path \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;132;01m{\u001b[39;00m\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mtimestamp\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m_exemplary_images.pdf\u001b[39m\u001b[38;5;124m'\u001b[39m\n\u001b[1;32m    320\u001b[0m \u001b[38;5;66;03m# Load the Excel file\u001b[39;00m\n\u001b[0;32m--> 321\u001b[0m xls \u001b[38;5;241m=\u001b[39m \u001b[43mpd\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mExcelFile\u001b[49m\u001b[43m(\u001b[49m\u001b[43mos\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mpath\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mjoin\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43moutput_dir\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mexcel_path\u001b[49m\u001b[43m)\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    322\u001b[0m df \u001b[38;5;241m=\u001b[39m pd\u001b[38;5;241m.\u001b[39mread_excel(xls, sheet_name\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mRaw Data\u001b[39m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m    324\u001b[0m \u001b[38;5;66;03m# Initialize PDF\u001b[39;00m\n",
      "File \u001b[0;32m~/Projects/AIA2/myenv/lib64/python3.9/site-packages/pandas/io/excel/_base.py:1550\u001b[0m, in \u001b[0;36mExcelFile.__init__\u001b[0;34m(self, path_or_buffer, engine, storage_options, engine_kwargs)\u001b[0m\n\u001b[1;32m   1548\u001b[0m     ext \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mxls\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1549\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[0;32m-> 1550\u001b[0m     ext \u001b[38;5;241m=\u001b[39m \u001b[43minspect_excel_format\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1551\u001b[0m \u001b[43m        \u001b[49m\u001b[43mcontent_or_path\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mpath_or_buffer\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstorage_options\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mstorage_options\u001b[49m\n\u001b[1;32m   1552\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1553\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m ext \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n\u001b[1;32m   1554\u001b[0m         \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mValueError\u001b[39;00m(\n\u001b[1;32m   1555\u001b[0m             \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mExcel file format cannot be determined, you must specify \u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1556\u001b[0m             \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124man engine manually.\u001b[39m\u001b[38;5;124m\"\u001b[39m\n\u001b[1;32m   1557\u001b[0m         )\n",
      "File \u001b[0;32m~/Projects/AIA2/myenv/lib64/python3.9/site-packages/pandas/io/excel/_base.py:1402\u001b[0m, in \u001b[0;36minspect_excel_format\u001b[0;34m(content_or_path, storage_options)\u001b[0m\n\u001b[1;32m   1399\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(content_or_path, \u001b[38;5;28mbytes\u001b[39m):\n\u001b[1;32m   1400\u001b[0m     content_or_path \u001b[38;5;241m=\u001b[39m BytesIO(content_or_path)\n\u001b[0;32m-> 1402\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m \u001b[43mget_handle\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1403\u001b[0m \u001b[43m    \u001b[49m\u001b[43mcontent_or_path\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43mrb\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mstorage_options\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mstorage_options\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mis_text\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mFalse\u001b[39;49;00m\n\u001b[1;32m   1404\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m \u001b[38;5;28;01mas\u001b[39;00m handle:\n\u001b[1;32m   1405\u001b[0m     stream \u001b[38;5;241m=\u001b[39m handle\u001b[38;5;241m.\u001b[39mhandle\n\u001b[1;32m   1406\u001b[0m     stream\u001b[38;5;241m.\u001b[39mseek(\u001b[38;5;241m0\u001b[39m)\n",
      "File \u001b[0;32m~/Projects/AIA2/myenv/lib64/python3.9/site-packages/pandas/io/common.py:882\u001b[0m, in \u001b[0;36mget_handle\u001b[0;34m(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)\u001b[0m\n\u001b[1;32m    873\u001b[0m         handle \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mopen\u001b[39m(\n\u001b[1;32m    874\u001b[0m             handle,\n\u001b[1;32m    875\u001b[0m             ioargs\u001b[38;5;241m.\u001b[39mmode,\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m    878\u001b[0m             newline\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[1;32m    879\u001b[0m         )\n\u001b[1;32m    880\u001b[0m     \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    881\u001b[0m         \u001b[38;5;66;03m# Binary mode\u001b[39;00m\n\u001b[0;32m--> 882\u001b[0m         handle \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mopen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mhandle\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mioargs\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mmode\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    883\u001b[0m     handles\u001b[38;5;241m.\u001b[39mappend(handle)\n\u001b[1;32m    885\u001b[0m \u001b[38;5;66;03m# Convert BytesIO or file objects passed with an encoding\u001b[39;00m\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: '..\\\\\\\\..\\\\\\\\outputs\\\\\\\\/20250403_102817\\\\/20250403_102817_results.xlsx'"
     ]
    }
   ],
   "source": [
    "aia.generate_pdf_from_excel()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "myenv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.18"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
